before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/keel
    id: "keel"
    binary: keel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X 'github.com/teamkeel/keel/runtime.Version={{.Version}}' -X 'github.com/teamkeel/keel/cmd.enabledDebugFlags=false'
archives:
  - builds:
     - keel
release:
  github:
    owner: teamkeel
    name: keel
  mode: append
  prerelease: true
checksum:
  name_template: "checksums.txt"