services:
  postgres:
    image: postgres:11.13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keel
    ports:
      - "8001:5432"
