services:
  postgres:
    image: postgres:11.13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=functions-runtime
    ports:
      - "7654:5432"
