name: Go

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    # - name: Build mobile api
    #   run: cd mobile-api && go build -v

    # - name: Build social
    #   run: cd social-service && go build -v

    # - name: Build explore
    #   run: cd explore && go build -v

    # - name: Test
    #   run: go test -v ./...