name: Create Release

on:
  workflow_call:
    inputs:
      branch:
        description: "The branch to run the release on"
        required: true
        type: string
      version:
        description: "Release Version"
        required: true
        type: string
      preRelease:
        required: false
        default: false
        type: boolean
      draft:
        required: false
        default: false
        type: boolean
      makeLatest:
        required: false
        default: true
        type: boolean
      generateChangelog:
        required: false
        default: false
        type: boolean
      releaseNotesURL:
        required: false
        type: string
      publishEvent:
        required: false
        type: boolean
        default: false
      eventBranch:
        required: false
        type: string
        default: "main"
      commitMessage:
        required: false
        type: string
        default: ""

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - run: git fetch --force --tags

      # creating a tag so goreleaser knows what to release
      - name: Create Release Tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ inputs.version }}"
          tag_exists_error: false
          message: "Keel release v${{ inputs.version }}"

      - name: Set variables for homebrew
        id: set-brew-envvars
        run: |
          {
            if [ ${{ inputs.preRelease }} == true ]; then
              repo="homebrew-keel-prerelease"
              alias="keel-prerelease"
            else
              repo="homebrew-keel"
              alias="keel"
            fi
            echo "HOMEBREW_REPO=$repo" >> "$GITHUB_OUTPUT"
            echo "HOMEBREW_ALIAS=$alias" >> "$GITHUB_OUTPUT"
          }

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: 1.13.0
          args: release
        #testing only
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        #   HOMEBREW_REPO: "homebrew-keel-prerelease"
        #   HOMEBREW_ALIAS: "keel-prerelease"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          HOMEBREW_REPO: ${{ steps.set-brew-envvars.outputs.HOMEBREW_REPO }}
          HOMEBREW_ALIAS: ${{ steps.set-brew-envvars.outputs.HOMEBREW_ALIAS }}

      - name: Update CHANGELOG
        id: changelog
        if: ${{ inputs.generateChangelog }}
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: "v${{ inputs.version }}"
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Get Changelog Output
        run: |
          echo "${{ steps.changelog.outputs.changelog }}"
          echo "${{ steps.changelog.outputs.changelog }}" >> $GITHUB_STEP_SUMMARY

      # Goreleaser won't update a draft release, so you have to update the release after to tune release params
      - name: Update goreleaser release with the changelogs
        id: update_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ inputs.version }}"
          name: "Keel release v${{ inputs.version }}"
          draft: ${{ inputs.draft }}
          allowUpdates: true
          updateOnlyUnreleased: true
          prerelease: ${{ inputs.preRelease }}
          makeLatest: ${{ inputs.makeLatest }}
          body: "Keel release v${{ inputs.version }}. Release notes can be found at ${{ inputs.releaseNotesURL || steps.changelog.outputs.changelog  }}"

      - name: Fire Release Event with Changelog
        if: ${{ inputs.publishEvent && inputs.generateChangelog }}
        id: release_event_changelog
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.PAT }}
          repository: teamkeel/backend
          event-type: "new-runtime-release"
          client-payload: '{"version": "${{ inputs.version }}", "changelog": "${{ steps.changelog.outputs.changelog }}", "baseBranch": "${{ inputs.eventBranch }}", "triggeringCommitMessage": "${{ inputs.commitMessage }}"}'

      - name: Fire Release Event
        if: ${{ inputs.publishEvent && inputs.generateChangelog  ==  false }}
        id: release_event
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.PAT }}
          repository: teamkeel/backend
          event-type: "new-runtime-release"
          client-payload: '{"version": "${{ inputs.version }}", "baseBranch": "${{ inputs.eventBranch }}", "triggeringCommitMessage": "${{ inputs.commitMessage }}"}'
