name: Lint JS packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-packages:
    name: Lint Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Pretier
        run: npm install -g prettier

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          prettier: true
          prettier_dir: ./packages
          commit_message: "chore: autofix prettier issues"

  lint-integration:
    name: Lint Integration
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Pretier
        run: npm install -g prettier

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          prettier: true
          commit_message: "chore: autofix prettier issues"
          prettier_dir: ./integration
