name: Prettier
on: [pull_request]

jobs:
  lint-packages:
    runs-on: ubuntu-latest
    name: Packages
    steps:
      - uses: actions/checkout@v2
      - uses: actionsx/prettier@v2
        with:
          args: --check packages

  lint-integration:
    runs-on: ubuntu-latest
    name: Integration Tests
    steps:
      - uses: actions/checkout@v2
      - uses: actionsx/prettier@v2
        with:
          args: --check integration/testdata
