name: New Release CLI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Keel version (tag)"
        required: true
        type: string
      isPrerelease:
        description: "Prerelease?"
        default: true
        required: true
        type: boolean

jobs:
  keel-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - run: git fetch --force --tags
      - name: Set variables for homebrew
        id: set-brew-envvars
        run: |
            {
                if [ ${{ inputs.isPrerelease }} == true ]; then
                    repo="homebrew-keel-prerelease"
                    alias="keel-prerelease"
                else
                    repo="homebrew-keel"
                    alias="keel"
                fi
                echo "HOMEBREW_REPO=$repo" >> "$GITHUB_OUTPUT"
                echo "HOMEBREW_ALIAS=$alias" >> "$GITHUB_OUTPUT"
            }
      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: 1.13.0
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
          HOMEBREW_REPO: ${{ steps.set-brew-envvars.outputs.HOMEBREW_REPO }}
          HOMEBREW_ALIAS: ${{ steps.set-brew-envvars.outputs.HOMEBREW_ALIAS }}
          GORELEASER_CURRENT_TAG: ${{ inputs.version }}
    