name: New Draft Release

on:
  push:
    tags:
      - "v*"

jobs:
  draft-release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Create Draft Release
        uses: elgohr/Github-Release-Action@v5
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            title: Keel runtime ${{ github.ref }}