name: OLD Publish Keel Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true
        type: string

jobs:
  setup:
    name: Checkout release branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: teamkeel/keel
          ref: "release/${{ inputs.version }}"
          fetch-depth: 0

  npm_release:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [
            "wasm",
            "functions-runtime",
            "testing-runtime",
            "client-react",
            "client-react-query",
          ]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          token: ${{ secrets.NPM_TOKEN }}

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.5.1

      - name: Set NPM packages to latest
        run: npm dist-tag add @teamkeel/${{ matrix.package }}@${{ inputs.version }} latest

  github_release:
    name: Make Github Release
    runs-on: ubuntu-latest
    needs: [npm_release]
    steps:
      - name: Publish Release
        id: publish_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ inputs.version }}"
          draft: false
          makeLatest: true
          prerelease: false
          allowUpdates: true
          updateOnlyUnreleased: true
