name: Make Pre Release

on:
  workflow_call:
    inputs:
      versionFormat:
        description: "Ref of where the release should be marked"
        required: true
        type: string
      publishTag:
        description: "Release Version"
        required: true
        type: string

jobs:
  setup:
    name: Generate Version
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.5.1

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      # generate a new version number based on semantic versioning
      - name: Generate version
        id: generate-version
        uses: paulhatch/semantic-version@v5.0.3
        with:
          tag_prefix: "v"
          major_pattern: "[A-Za-z]+.*!:"
          major_regexp_flags: "g"
          minor_pattern: "^(feat|fix)(\\(.*\\))?: .*$"
          version_format: ${{ inputs.versionFormat}}

      - name: Print release version
        run: echo "NEW_VERSION=${{ steps.generate-version.outputs.version }}"

    outputs:
      version: ${{ steps.generate-version.outputs.version }}

  npm_release:
    needs: [setup]
    uses: ./.github/workflows/npm_release.yml
    with:
      version: ${{ needs.setup.outputs.version }}
      publishTag: ${{ inputs.publishTag }}
      dryRun: false
    secrets: inherit

  github_release:
    needs: [setup, npm_release]
    uses: ./.github/workflows/github_release.yml
    with:
      branch: ${{ github.event.ref || github.head_ref }}
      version: ${{ needs.setup.outputs.version }}
      preRelease: true
      draft: false
      makeLatest: false
      generateChangelog: true
      publishEvent: ${{ github.event_name != 'workflow_dispatch' }}
      commitMessage: ${{ github.event.head_commit.message }}
    secrets: inherit
