name: Semantic Release

on: 
  push:
    branches: 
      - next
      - prerelease
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"   
        required: true
        default: main
        type: string
        
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semantic.outputs.outputs.new_release_version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        ref: "${{ inputs.branch }}"
        fetch-depth: 0
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 20.9.0
    - name: NPM install
      run: npm install
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 21.1.1
        extra_plugins: |
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.KEEL_CI_SEMANTIC_RELEASE }}
    - name: Version tag created
      run: |
        echo ${{ steps.semantic.outputs.new_release_version }}

  go-releaser:
    needs: semantic-release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:  
        persist-credentials: false
        ref: "${{ needs.semantic-release.outputs.new_version }}"
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.KEEL_CI_SEMANTIC_RELEASE }}