name: Test NPM packages

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-sdk:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sdk
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: ./functions/sdk
        run: npm install && npm test
  test-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: ./testing/package
        run: npm install && npm test
