name: Test NPM packages
on: [pull_request]

jobs:
  test-functions-runtime:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: functions-runtime
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/checkout@v3
      - name: Install deps
        working-directory: ./packages/functions-runtime
        run: pnpm install --frozen-lockfile
      - name: Run tests
        working-directory: ./packages/functions-runtime
        run: pnpm run test

  test-testing-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/checkout@v3
      - name: Install deps
        working-directory: ./packages/testing-runtime
        run: pnpm install --frozen-lockfile
      - name: Run tests
        working-directory: ./packages/testing-runtime
        run: pnpm run test

  test-sdk:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sdk
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: ./packages/sdk
        run: npm install && npm test
  test-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: ./packages/testing
        run: npm install && npm test
