name: Update SDKs dist-tags
run-name: Update SDKs ${{ inputs.version }} with '${{ inputs.publishTag }}'

# Currently not working due to authorisation issue

on:
  workflow_dispatch:
    inputs:
      version:
        description: "NPM version to update (e.g. 0.370.0)"
        required: true
        type: string
      publishTag:
        description: "New distribution tag"
        required: true
        default: "latest"
        type: string

jobs:
  npm_release:
    name: NPM Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [
            "wasm",
            "functions-runtime",
            "testing-runtime",
            "client-react",
            "client-react-query",
          ]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          token: ${{ secrets.NPM_TOKEN }}
      - name: Adding `${{ inputs.publishTag }}` tag to ${{ matrix.package }}@${{ inputs.version }} 
        run: npm dist-tag add @teamkeel/${{ matrix.package }}@${{ inputs.version }} ${{ inputs.publishTag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}