name: Test WASM compilation
on: [pull_request]

jobs:
  test-wasm-compilation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - name: Generate wasm binary
        run: make wasm